// Mocks generated by Mockito 5.4.2 from annotations
// in merokaam/test/layers/presentation/job_profile/bloc/job_profile_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as i5;

import 'package:dartz/dartz.dart' as i3;
import 'package:merokaam/core/errors/failures.dart' as i6;

import 'package:merokaam/core/models/job_profile_model.dart' as i7;
import 'package:merokaam/core/usecases/usecase.dart' as i9;
import 'package:merokaam/layers/domain/job_profile/repositories/job_profile_repositories.dart' as i2;
import 'package:merokaam/layers/domain/job_profile/usecases/delete_job_profile.dart' as i4;
import 'package:merokaam/layers/domain/job_profile/usecases/read_job_profile.dart' as i8;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeJobProfileRepository_0 extends i1.Fake implements i2.JobProfileRepository {}

/// A class which mocks [DeleteJobProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteJobProfile extends i1.Mock implements i4.DeleteJobProfile {
  MockDeleteJobProfile(any) {
    i1.throwOnMissingStub(this);
  }
  int id = 1;

  @override
  i5.Future<i3.Either<i6.Failure, int>?> call(id) =>
      (super.noSuchMethod(Invocation.method(#call, [int]), returnValue: Future<i3.Either<i6.Failure, int>?>.value())
          as i5.Future<i3.Either<i6.Failure, int>?>);
}

/// A class which mocks [ReadJobProfiles].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadJobProfiles extends i1.Mock implements i8.ReadJobProfile {
  MockReadJobProfiles() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.JobProfileRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository), returnValue: _FakeJobProfileRepository_0()) as i2.JobProfileRepository);
  @override
  i5.Future<i3.Either<i6.Failure, List<i7.JobProfileModel>>?> call(i9.NoParams? noParams) =>
      (super.noSuchMethod(Invocation.method(#call, [noParams]), returnValue: Future<i3.Either<i6.Failure, List<i7.JobProfileModel>>?>.value())
          as i5.Future<i3.Either<i6.Failure, List<i7.JobProfileModel>>?>);
}
