// Mocks generated by Mockito 5.4.4 from annotations
// in merokaam/test/layers/data/login/repositories/login_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:merokaam/core/entities/login.dart' as _i5;
import 'package:merokaam/core/entities/user_info_response.dart' as _i2;
import 'package:merokaam/core/network/network_info.dart' as _i6;
import 'package:merokaam/layers/data/login/datasources/login_remote_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserInfoResponse_0 extends _i1.SmartFake
    implements _i2.UserInfoResponse {
  _FakeUserInfoResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRemoteDataSource extends _i1.Mock
    implements _i3.LoginRemoteDataSource {
  MockLoginRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserInfoResponse> login(_i5.LoginModel? loginModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginModel],
        ),
        returnValue:
            _i4.Future<_i2.UserInfoResponse>.value(_FakeUserInfoResponse_0(
          this,
          Invocation.method(
            #login,
            [loginModel],
          ),
        )),
      ) as _i4.Future<_i2.UserInfoResponse>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
