// Mocks generated by Mockito 5.4.4 from annotations
// in merokaam/test/layers/presentation/job_profile/read_job_profile/bloc/job_profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i5;
import 'package:merokaam/core/entities/job_profile.dart' as _i7;
import 'package:merokaam/core/errors/failures.dart' as _i6;
import 'package:merokaam/layers/domain/job_profile/repositories/job_profile_repositories.dart'
    as _i2;
import 'package:merokaam/layers/domain/job_profile/usecases/read_job_profile.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJobProfileRepository_0 extends _i1.SmartFake
    implements _i2.JobProfileRepository {
  _FakeJobProfileRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReadJobProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadJobProfile extends _i1.Mock implements _i3.ReadJobProfile {
  MockReadJobProfile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JobProfileRepository get jobProfileRepository => (super.noSuchMethod(
        Invocation.getter(#jobProfileRepository),
        returnValue: _FakeJobProfileRepository_0(
          this,
          Invocation.getter(#jobProfileRepository),
        ),
      ) as _i2.JobProfileRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.JobProfile>?> call(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i7.JobProfile>?>.value(),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.JobProfile>?>);
}
