// Mocks generated by Mockito 5.4.4 from annotations
// in merokaam/test/layers/data/job_profile/repositories/job_profile_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:merokaam/core/models/job_profile_model.dart' as _i4;
import 'package:merokaam/core/network/network_info.dart' as _i6;
import 'package:merokaam/layers/data/job_profile/data_sources/job_profile_local_data_source.dart' as _i2;
import 'package:merokaam/layers/data/job_profile/data_sources/job_profile_remote_data_sources.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JobProfilesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobProfilesLocalDataSource extends _i1.Mock implements _i2.JobProfilesLocalDataSource {
  MockJobProfilesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.JobProfileModel>> readLastJobProfiles() => (super.noSuchMethod(
        Invocation.method(
          #readLastJobProfiles,
          [],
        ),
        returnValue: _i3.Future<List<_i4.JobProfileModel>>.value(<_i4.JobProfileModel>[]),
      ) as _i3.Future<List<_i4.JobProfileModel>>);

  @override
  _i3.Future<void>? cacheJobProfile(_i4.JobProfileModel? jobProfileModel) => (super.noSuchMethod(
        Invocation.method(
          #cacheJobProfile,
          [jobProfileModel],
        ),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>?);
}

/// A class which mocks [JobProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobProfileRemoteDataSource extends _i1.Mock implements _i5.JobProfileRemoteDataSource {
  MockJobProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.JobProfileModel>> readJobProfiles() => (super.noSuchMethod(
        Invocation.method(
          #readJobProfile,
          [],
        ),
        returnValue: _i3.Future<List<_i4.JobProfileModel>>.value(<_i4.JobProfileModel>[]),
      ) as _i3.Future<List<_i4.JobProfileModel>>);

  @override
  _i3.Future<int> deleteJobProfile(int? userAccountId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJobProfile,
          [userAccountId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> createJobProfile(_i4.JobProfileModel? postModel) => (super.noSuchMethod(
        Invocation.method(
          #createJobProfile,
          [postModel],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateJobProfile(_i4.JobProfileModel? postModel) => (super.noSuchMethod(
        Invocation.method(
          #updateJobProfile,
          [postModel],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
